---
title: "narwhal_habitat_model"
author: "Marie Zahn"
date: '2022-12-12'
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load packages}
library(tidyverse)
library(corrplot)
library(MuMIn)
library(arm)
library(faraway)
library(ggplot2)
library(sjPlot)
```


```{r select data before freeze-up}
## since we know narwhals cannot survive in Melville Bay after the freeze up, we will select data from before the fast ice comes in
## here, I define the freeze up date as the day when sea ice > 75%

## freeze up date in 2018
head(model_data_pooled %>% dplyr::filter(ice_cover_percent>75,year==2018))
# 2018-10-28 which is equal to DOY=301 # sverdrup froze up first

## freeze up date in 2019
model_data_pooled %>% dplyr::filter(ice_cover_percent>75,year==2019,DOY>100)
# 2019-12-23 which is equal to DOY=357 # rink froze up first

## filter all data before these dates
# not pooled
mdl_data_open_water2018 <- model_data %>% filter(year==2018) %>% 
  filter(DOY<301)
mdl_data_open_water2019 <- model_data %>% filter(year==2019) %>% 
  filter(DOY>100,DOY<357)

# pooled
mdl_data_open_water2018_pool <- model_data_pooled %>% filter(year==2018) %>% 
  filter(DOY<301)
mdl_data_open_water2019_pool <- model_data_pooled %>% filter(year==2019) %>% 
  filter(DOY>100,DOY<357)

# sanity check plots
qplot(as.Date(time),ice_cover_percent, geom="point", data = mdl_data_open_water2018)
qplot(as.Date(time),ice_cover_percent, geom="point", data = mdl_data_open_water2019)

## join both datasets
mdl_data_b4freeze <- rbind(mdl_data_open_water2018, mdl_data_open_water2019)
mdl_data_b4freeze_pooled <- rbind(mdl_data_open_water2018_pool, mdl_data_open_water2019_pool)

qplot(as.Date(time),ice_cover_percent, geom="point", data = mdl_data_b4freeze_pooled)
```


## Run models

Got warning message when sea ice was included:
Warning message:
glm.fit: fitted probabilities numerically 0 or 1 occurred 

When I removed sea ice cover, the warning was gone.

```{r run glm | all sites}
## logistic regression 
## glm with binomial response and logit link ===========================

# Model using unscaled data -------------------------------------------

## model with 'device' variable (unpooled detections)
mdl_global <- glm(narwhal ~
                    temp_surf+
                    temp_deep+
                    salt_surf+
                    salt_deep+
                    ice_cover_percent+
                    runoff_racmo+
                    glacier_length+
                    device+
                    site+
                    DOY,
                  data = mdl_data_b4freeze,
                  family=binomial(link="logit"),
                  na.action="na.fail")

# print summary output
summary(mdl_global)
faraway::sumary(mdl_global)

par(mfrow = c(2,2))
plot(mdl_global)
plot_model(mdl_global,type="pred")

## model without 'device' (pooled detections)
mdl_global_pooled <- glm(narwhal ~
                           temp_surf+
                           temp_deep+
                           salt_surf+
                           salt_deep+
                           ice_cover_percent+
                           runoff_racmo+
                           glacier_length+
                           site+
                           DOY,
                         data = mdl_data_b4freeze_pooled,
                         family=binomial(link="logit"),na.action="na.fail")

# print summary output
summary(mdl_global_pooled)
faraway::sumary(mdl_global_pooled)

par(mfrow = c(2,2))
plot(mdl_global_pooled)
plot_model(mdl_global_pooled,type="pred")

```

Run separate glm for each glacier/site. Here I only use pooled datasets (=no device variable)

```{r run glm | model for each site}
## Rink/Fisher ---------------------------------------------
mdl_data_rink <- mdl_data_b4freeze_pooled %>% filter(site=='rink')
mdl_rink <- glm(narwhal ~ temp_surf+temp_deep+salt_surf+salt_deep+
                  ice_cover_percent+runoff+glacier_length+DOY,
                data = mdl_data_rink,family=binomial(link="logit"),na.action="na.fail")
summary(mdl_rink)
par(mfrow = c(2,2))
plot(mdl_rink)

## Kong Oscar ----------------------------------------------
mdl_data_kong <- mdl_data_b4freeze_pooled %>% filter(site=='kong')
mdl_kong <- glm(narwhal ~ temp_surf+temp_deep+salt_surf+salt_deep+
                  ice_cover_percent+runoff+glacier_length+DOY,
    data = mdl_data_kong,family=binomial(link="logit"),na.action="na.fail")
summary(mdl_kong)
par(mfrow = c(2,2))
plot(mdl_kong)

## Sverdrup ------------------------------------------------
mdl_data_sver <- mdl_data_b4freeze_pooled %>% filter(site=='sver')
mdl_sver <- glm(narwhal ~ temp_surf+temp_deep+salt_surf+salt_deep+
                  ice_cover_percent+runoff+glacier_length+DOY,
    data = mdl_data_sver,family=binomial(link="logit"),na.action="na.fail")
summary(mdl_sver)
par(mfrow = c(2,2))
plot(mdl_sver)

```


## Diagnostics

```{r diagnostics}
## plot deviance residuals------------------------------------------
## set plot area
par(mai = c(0.9, 0.9, 0.1, 0.1),
omi = c(0, 0, 0, 0),
cex.lab = 1)
## plot resids vs eta
binnedplot(fitted(mdl_global_pooled), 
           residuals(mdl_global_pooled), las = 1, pch = 16,
           ylab = "Residuals", xlab = "Fitted values",main = "")

## compute R^2
# deviances
nn <- length(mdl_data_b4freeze_pooled$time)
DM_mod <- mdl_global_pooled$deviance
D0_mod <- mdl_global_pooled$null.deviance
# R^2
(R2 <- (1 - exp((DM_mod - D0_mod) / nn)) / (1 - exp(-D0_mod / nn)))

## leverages--------------------------------------------------------
## set plot area
par(mai = c(0.9, 1, 0.1, 0.1),
omi = c(0, 0, 0, 0),
cex.lab = 1)
levs <- hatvalues(mdl_global_pooled)
## threshhold value
h_crit <- 2 * length(coef(mdl_global_pooled)) / nn

## halfnormal plot
faraway::halfnorm(levs, las = 1, ylab = "")
text(0, 0.92*par("usr")[4], substitute(italic(h[crit]) == h_crit, 
                                       list(h_crit = h_crit)), pos = 4)
mtext(side = 2, text = "Sorted Data", line = 4)

## Cook's D---------------------------------------------------------
## set plot area
par(mai = c(0.9, 0.9, 0.1, 0.1),
omi = c(0, 0, 0, 0),
cex.lab = 1)
## halfnormal plot
CD <- cooks.distance(mdl_global_pooled)
faraway::halfnorm(CD, las = 1, ylab = "")
mtext(side = 2, text = "Sorted Data", line = 3.5)

## H-L test with 8 groups
# A non-significant p value indicates that there is no evidence that the observed and expected frequencies differ (i.e., evidence of good fit).
library(generalhoslem)
generalhoslem::logitgof(obs = mdl_data_b4freeze_pooled$narwhal,
                        exp = fitted(mdl_global_pooled), g = 8)
```


```{r scaled data}
# Models using scaled data -------------------------------------------

mdl_ice <- glm(narwhal ~
                    temp_surf,data = model_data_pooled,
                  family=binomial(link="logit"),na.action="na.fail")

# model with device - SCALED
mdl_global <- glm(narwhal ~
                    runoff+site+salt_surf+salt_deep+temp_surf+
                    temp_deep+ice_cover_percent+site_length+DOY,
    data = model_data_scale,family=binomial(link="logit"),na.action="na.fail")

# model with device - SCALED
mdl_global <- glmmTMB(narwhal ~
                    runoff+I(runoff^2)+
                    site+salt_surf+salt_deep+temp_surf+
                    temp_deep+ice_cover_percent+glacier_length+DOY,
    data = model_data_scale,family=binomial(link="logit"),na.action="na.fail")

# print summary output
summary(mdl_global)
par(mfrow = c(2,2))
plot(mdl_global)
plot_model(mdl_global,type="pred")

```


```{r dredge}
## use dredge function to run all model combinations ======================
dredge_mdl <- dredge(mdl_global_pooled)
dredge_mdl
```



```{r}
library(sjPlot)
```


```{r fit best model}
# model with 'device' variable
mdl_best <- glm(narwhal ~ site+glacier_length+runoff+salt_deep+ice_cover_percent,
                  data = mdl_data_b4freeze_pooled,family=binomial(link="logit"),na.action="na.fail")

summary(mdl_best)
plot_model(mdl_best, type='pred',ci.lvl = NA)

## plot deviance residuals------------------------------------------
## set plot area
par(mai = c(0.9, 0.9, 0.1, 0.1),
omi = c(0, 0, 0, 0),
cex.lab = 1)
## plot resids vs eta
binnedplot(fitted(mdl_best), residuals(mdl_best), las = 1, pch = 16,
ylab = "Residuals", xlab = "Fitted values",
main = "")

## compute R^2
# deviances
nn <- length(mdl_data_b4freeze_pooled$time)
DM_mod <- mdl_best$deviance
D0_mod <- mdl_best$null.deviance
# R^2
(R2 <- (1 - exp((DM_mod - D0_mod) / nn)) / (1 - exp(-D0_mod / nn)))

```

```{r check autocorrelation}
acf(resid(mdl_global_pooled))
```


```{r RUN MODEL}
library(sjPlot)
library(lme4)
library(MuMIn)

model_data <- model_vars_df %>% mutate_at(vars(runoff,salt_surf,temp_surf,salt_deep,temp_deep,ice_cover_percent,
                                 velocity,glacier_length,DOY),scale) %>% 
  mutate_at(vars(runoff,salt_surf,temp_surf,salt_deep,temp_deep,ice_cover_percent,
                                 velocity,glacier_length,DOY),as.numeric) %>% drop_na()

samwise <- glm(narwhal ~ runoff+site+salt_surf+salt_deep+temp_surf+temp_deep+ice_cover_percent+velocity+glacier_length+DOY,
    data = model_data,family=binomial(link="logit"),na.action="na.fail")
summary(samwise)
par(mfrow = c(2,2))
plot(samwise)

samwise_dredge <- dredge(samwise)


plot_model(samwise,type="pred")

samwise <- glm(narwhal ~ runoff+site+salt_surf+ice_cover_percent+velocity+DOY,
    data = model_data,family=binomial(link="logit"),na.action="na.fail")
summary(samwise)

plot_model(samwise,type="pred")


library(mgcv)

matwise <- gam(narwhal ~ s(runoff)+site+s(salt_surf)+s(salt_deep)+s(temp_surf)+s(temp_deep)+s(ice_cover_percent)+s(velocity)+s(glacier_length)+s(DOY, bs = "cc"),
    data = model_data,family=binomial(link="logit"),na.action="na.fail")

matwise <- gam(narwhal ~ site+s(salt_surf)+s(salt_deep)+s(temp_surf)+s(temp_deep)+s(glacier_length)+s(DOY, bs = "cc"),
    data = model_data,family=binomial(link="logit"),na.action="na.fail")

par(mfrow = c(2,2))
gam.check(matwise)
dev.off()

summary(matwise)

library("mgcViz")
print(plot(getViz(matwise), allterms = T), pages = 1)

```

